#!/bin/bash

echo -n "Sisesta kuu number: "
read kuu

if [[ $kuu -ge 1 ]] && [[ $kuu -le 2 ]]
then
	echo "Praegu on talv"
elif [[ $kuu -ge 3 ]] && [[ $kuu -le 5 ]]
then
	echo "praegu on kevad"
elif [[ $kuu -ge 6 ]] && [[ $kuu -le 8 ]]
then
	echo "praegu on suvi"
elif [[ $kuu -ge 9 ]] && [[ $kuu -le 12 ]]
then
	echo "praegu on talv"
fi
