#!/bin/bash

summa=0
for (( arv=1; arv<11; arv++ )) #Arvud on vahemikus 1-10
do
	jaak=$(($arv % 2)) #arv jagatakse kahega
	if [ $jaak -eq 0 ]; then #Kui jääk jääb 0
		summa=$(($summa + $arv)) #liidetakse
		echo $summa
	fi
done
echo "Arvude vahemikus 1 kuni 10(kaasaarvatud) paarisarvude summa on :$summa"
