#! /bin/bash
#
# muljed
#
echo "Rauno Borovkov" #
echo "ISP117" #
echo "Aine on põnev ming paneb ise lahendusi otsima, et kuidas saaks asja lahendada kiiremini ja efektiivsemalt" #
echo "Loodan, et saan aine kohta palju rohkem teada, sest see on põnev" #
#
#
